app.logging.level=INFO
app.repository.type=database
app.env=DEVELOPMENT

db.url=jdbc:mysql://localhost:3306/quantity_measurement
db.username=root
db.password=2118211
db.driver=com.mysql.cj.jdbc.Driver
db.pool.size=5
db.test.query=SELECT 1
