# -------------------------------
# Application Configuration
# -------------------------------
spring.application.name=quantity-measurement-app
server.port=8080


# -------------------------------
# Repository Type
# -------------------------------
repository.type=database


# -------------------------------
# MySQL Database Configuration
# -------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_entity
spring.datasource.username=root
spring.datasource.password=2118211
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# -------------------------------
# JPA / Hibernate Configuration
# -------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# -------------------------------
# Hikari Connection Pool
# -------------------------------
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


# -------------------------------
# Logging Configuration
# -------------------------------
logging.level.root=INFO
logging.level.com.app.quantity_measurement_app=DEBUG
logging.level.org.hibernate.SQL=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36}:%line - %msg%n


# -------------------------------
# Swagger / OpenAPI
# -------------------------------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


# -------------------------------
# Actuator
# -------------------------------
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always